dist: xenial
language: c

compiler:
- gcc

jobs:
  include:
  - stage: First project
    before_script:
    - cmake .
    - cmake --build .
    script:
    - cd proj1; bash runTests.sh


jobs:
  include:
  - stage: Second project
    before_script:
    - cmake .
    - cmake --build .
    script:
    - cd proj2; bash runTests.sh